config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :bookings, only: [:index, :show]

  get "/pages/dashboard" => "pages#dashboard"

  resources :cars, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :car_bookings, through: :bookings
  has_many :bookings
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params.merge(car_id: params[:car_id]))
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'cars/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      @cars = Car.where("brand ILIKE ?", params[:query])
    else
      @cars = Car.all
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.title = "#{@car.brand} #{@car.model}"
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new

    @markers =
      [{
        lat: @car.latitude,
        lng: @car.longitude
      }]
  end

  private

  def car_params
    params.require(:car).permit(:brand, :year, :model, :description, :price, :range, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
    @user = current_user
    return unless @user

    @bookings = @user.bookings
    @cars = @user.cars
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Your bookings!</h1>

app/views/bookings/show.html.erb
<div class=" card mx-auto text-center">
  <div class="card-body">
    <h5 class="card-title">Booking Confirmed! Thank you for using Current.</h5>
    <p class="card-text">Here is a summary of your booking:</p>
      <ul>
        <li style="list-style-type:none">Car: <%= @booking.car.title %></li>
        <li style="list-style-type:none">Booked for: <%= @booking.start_date %> - <%= @booking.end_date %></li>
        <li style="list-style-type:none">Price: $<%= @booking.car.price %>/day</li>
      </ul>
    <%= link_to 'Return to Dashboard', pages_dashboard_path, :class => "btn btn-primary" %>
    <%= link_to 'Book Another Car', cars_path, :class => "btn btn-primary" %>
  </div>
</div>

app/views/cars/index.html.erb
<div class="text-center mt-3"></div>

<div class="d-flex flex-wrap justify-content-between">
  <% @cars.reverse.each do |car| %>
    <div class="card card-index">
      <% if car.photos.attached? %>
        <%= cl_image_tag car.photos.first.key, class: "card-img-top" %>
      <% end %>
      <div class="card-body">
        <p class="index-title"><strong><%= car.title %></strong></p>
        <p>Year: <%= car.year %></p>
        <p>Price: $<%= car.price %>/day</p>
        <div class="text-center">
          <%= link_to "View More", car_path(car), class: "btn btn-primary" %>
        </div>
      </div>
     </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="card mx-auto">
    <div class="card-body">
      <h2 class="text-center">List Car</h2>
        <%= simple_form_for @car do |f| %>
          <%= f.input :brand %>
          <%= f.input :model %>
          <%= f.input :year %>
          <%= f.input :price %>
          <%= f.input :description %>
          <%= f.input :range %>
          <%= f.input :address %>
          <%= f.input :photos, as: :file, input_html: {multiple: true} %>
      <div class="text-center">
      <%= f.submit 'List Car', class: 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container mt-3">
  <div class="show-card">
    <% if @car.photos.attached? %>
      <div id="Mycarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
           <% @car.photos.each_with_index do |photo, n| %>
             <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
          <% end %>
        </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <%= cl_image_tag @car.photos.first.key, class: 'd-block w-100' %>
        </div>
          <% @car.photos.drop(1).each do |photo| %>
        <div class="carousel-item">
          <%= cl_image_tag photo.key, class: 'd-block w-100' %>
        </div>
        <% end %>
        </div>
         <a class="carousel-control-prev" href="#Mycarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#Mycarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
  </div>
  <div class="card w-100 mx-auto d-flex flex-row justify-content-between">
    <div class="card-body">
      <h3 class="card-title"><strong><%= @car.title %> </strong></h3>
      <p class="card-text"><strong>Year: </strong><%= @car.year %></p>
      <p class="card-text"><strong>Price: </strong>$<%= @car.price %>/day</p>
      <p class="card-text"><strong>Contact: </strong><%= @car.user.email %></h5>
      <p class="card-text"><strong>Description: </strong><%= @car.description %></p>
      <p class="card-text"><strong>Range: </strong><%= @car.range %> km</p>
      <p class="card-text"><strong>Address: </strong><%= @car.address %></p>
    </div>
    <div class="card-body">
      <h5 class="card-title text-center">Book Car</h5>
      <%= simple_form_for [@car, @booking] do |f| %>
        <div class="form-inputs">
            <%= f.input  :start_date%>
            <%= f.input :end_date %>
        </div>
        <div class="form-actions text-center">
            <%= f.submit 'Book Car', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Current</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar'  %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<% if @user %>
<div class="card-dashboard" style="width:500px; margin: 16px auto;">
  <p class="text-center">Welcome, <%=@user.email%>!</p>
  <ul class="nav nav-pills mb-3 d-flex justify-content-center" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">My Bookings</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">My Booked Cars</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">My Cars</a>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab"><%= render 'shared/bookings' %></div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab"><%= render 'shared/carsBookings' %></div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab"><%= render 'shared/cars' %></div>
  </div>
</div>
<% else %>
  <%= render 'shared/logout' %>
<% end %>

app/views/shared/_bookings.html.erb
<div class="card">
  <div class="card-body">
  <h2>My Bookings</h2>
  <% @bookings.reverse.each do |booking| %>
    <strong><%= booking.car.title %></strong> <%= link_to "View car", car_path(booking.car) %>
    <p>Booked for: <%= booking.start_date %> - <%= booking.end_date %> </p>
  <% end %>
  </div>
</div>

app/views/shared/_cars.html.erb
<div class="card">
  <div class="card-body">
  <h3>My Car Listings</h3>
  <% @cars.each do |car| %>
    <li style="list-style-type:none"> <strong><%= car.title %></strong> <%= link_to "View listing", car_path(car) %></li>
  <% end %>
  </div>
</div>

app/views/shared/_carsBookings.html.erb
<div class="card">
  <div class="card-body">
<h2>My Booked Cars</h2>
<% @cars.each do |car| %>
  <% car.bookings.each do |booking| %>
    <strong><%= booking.car.title %></strong>
    <p>Booked for: <%= booking.start_date %> - <%= booking.end_date %> </p>
  <% end %>
<% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="container">
<div class="row" style="height: 725px;">
  <div class="col-6 text-center float-left px-0" style="background-image: url(https://images.unsplash.com/photo-1571987502227-9231b837d92a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80); background-size: cover; height: 100%;"></div>
  <div class="col-6 d-flex justify-content-center h-100">
    <div class="card my-auto mx-auto" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Welcome to Current</h5>
        <p class="card-text">Log in to rent or list electric cars.</p>
        <div class="text-center">
          <%= link_to 'Log In', new_user_session_path, :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_logout.html.erb
<div class="row" style="height: 725px;">
  <div class="col-6 text-center float-left px-0" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.2) 50%), url(https://images.unsplash.com/photo-1571987502227-9231b837d92a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80); background-size: cover; height: calc(100vh -70px);"></div>
  <div class="col-6 d-flex justify-content-center h-100">
    <div class="card my-auto mx-auto" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">You are signed out</h5>
        <p class="card-text">Log in to view your current bookings and all available electric cars.</p>
        <div class="text-center">
          <%= link_to 'Log In', new_user_session_path, :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="navbar-brand">
    <%= link_to(root_path) do %>
    <%= render 'shared/logo' %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Dashboard', pages_dashboard_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Book Car', cars_path, class: 'nav-link'  %>
      </li>
      <li class="nav-item active">
        <%= link_to 'List Car', new_car_path, class: 'nav-link'  %>
      </li>
    </ul>
  </div>
  <div class="form-inline collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ml-auto d-flex flex-row">
      <%= form_tag cars_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control mr-sm-2",
    placeholder: "Find a Car" %>
  <%= submit_tag "Search", class: "btn btn-outline-success" %>
<% end %>
      <% if current_user.present? %>
        <%= link_to 'Log Out', destroy_user_session_path, :method => :delete, class: 'btn btn-outline-success my-2 my-sm-0 ml-2' %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path, class: 'btn btn-outline-success my-2 my-sm-0 ml-2' %>
      <% end %>
    </div>
  </div>
</nav>